"""Shared data models for the PetGen pipeline."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

import numpy as np


class BreedGroup(str, Enum):
    SMALL_DOG = "small_dog"
    MEDIUM_DOG = "medium_dog"
    LARGE_DOG = "large_dog"
    PUPPY = "puppy"
    CAT = "cat"
    KITTEN = "kitten"


class AspectRatio(str, Enum):
    VERTICAL = "9:16"
    SQUARE = "1:1"
    LANDSCAPE = "16:9"


class GeminiModel(str, Enum):
    NANO_BANANA_2 = "gemini-3.1-flash-image"  # Best balance
    NANO_BANANA_PRO = "gemini-3-pro-image-preview"  # Highest quality
    NANO_BANANA_FAST = "gemini-2.5-flash-image"  # Fastest


@dataclass
class VoiceSettings:
    """Voice configuration for a character."""

    preset_name: str | None = None
    reference_clip: Path | None = None
    exaggeration: float = 0.7
    pitch_shift: float = 0.0
    speed: float = 1.0


@dataclass
class CharacterProfile:
    """A persistent pet character with visual identity and voice."""

    id: str
    name: str
    breed: str
    breed_group: BreedGroup
    reference_images: list[Path]
    canonical_poses: dict[str, Path] = field(default_factory=dict)
    voice: VoiceSettings = field(default_factory=VoiceSettings)
    personality_tags: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def save(self, directory: Path) -> Path:
        """Serialize character profile to JSON."""
        import json

        directory.mkdir(parents=True, exist_ok=True)
        path = directory / f"{self.id}.json"
        data = {
            "id": self.id,
            "name": self.name,
            "breed": self.breed,
            "breed_group": self.breed_group.value,
            "reference_images": [str(p) for p in self.reference_images],
            "canonical_poses": {k: str(v) for k, v in self.canonical_poses.items()},
            "voice": {
                "preset_name": self.voice.preset_name,
                "reference_clip": str(self.voice.reference_clip) if self.voice.reference_clip else None,
                "exaggeration": self.voice.exaggeration,
                "pitch_shift": self.voice.pitch_shift,
                "speed": self.voice.speed,
            },
            "personality_tags": self.personality_tags,
            "metadata": self.metadata,
        }
        path.write_text(json.dumps(data, indent=2))
        return path

    @classmethod
    def load(cls, path: Path) -> CharacterProfile:
        """Deserialize character profile from JSON."""
        import json

        data = json.loads(path.read_text())
        voice_data = data.get("voice", {})
        ref_clip = voice_data.get("reference_clip")
        return cls(
            id=data["id"],
            name=data["name"],
            breed=data["breed"],
            breed_group=BreedGroup(data["breed_group"]),
            reference_images=[Path(p) for p in data["reference_images"]],
            canonical_poses={k: Path(v) for k, v in data.get("canonical_poses", {}).items()},
            voice=VoiceSettings(
                preset_name=voice_data.get("preset_name"),
                reference_clip=Path(ref_clip) if ref_clip else None,
                exaggeration=voice_data.get("exaggeration", 0.7),
                pitch_shift=voice_data.get("pitch_shift", 0.0),
                speed=voice_data.get("speed", 1.0),
            ),
            personality_tags=data.get("personality_tags", []),
            metadata=data.get("metadata", {}),
        )


@dataclass
class BoundingBox:
    """Face bounding box."""

    x1: float
    y1: float
    x2: float
    y2: float
    confidence: float = 0.0

    @property
    def width(self) -> float:
        return self.x2 - self.x1

    @property
    def height(self) -> float:
        return self.y2 - self.y1

    @property
    def center(self) -> tuple[float, float]:
        return ((self.x1 + self.x2) / 2, (self.y1 + self.y2) / 2)


@dataclass
class Landmark:
    """A single facial landmark point."""

    x: float
    y: float
    visibility: float = 1.0  # 0=occluded, 1=visible


@dataclass
class MotionSequence:
    """A sequence of motion parameters generated by JoyVASA."""

    keypoints: np.ndarray  # (T, N, 2) — T frames, N keypoints, x/y
    expressions: np.ndarray  # (T, D) — expression coefficients
    fps: float = 25.0

    @property
    def num_frames(self) -> int:
        return self.keypoints.shape[0]

    @property
    def duration(self) -> float:
        return self.num_frames / self.fps


@dataclass
class AnimationConfig:
    """Configuration for the animation pipeline."""

    fps: int = 25
    resolution: tuple[int, int] = (1080, 1920)  # width, height (vertical)
    aspect_ratio: AspectRatio = AspectRatio.VERTICAL
    mouth_amplitude_limit: float = 0.8  # 0-1, limits mouth opening to reduce dark-blob
    breathing_bpm: float | None = None  # Auto-detect from breed if None
    enable_ear_twitches: bool = True
    enable_head_bob: bool = True
    enable_blinks: bool = True
    enable_tail_wag: bool = True
    blink_interval: tuple[float, float] = (3.0, 6.0)
    deflicker: bool = True


@dataclass
class PipelineResult:
    """Result of a full pipeline run."""

    video_path: Path
    audio_path: Path
    character: CharacterProfile
    scene_image: Path | None = None
    duration: float = 0.0
    num_frames: int = 0
    metadata: dict[str, Any] = field(default_factory=dict)
